test_that("process DIF and drift summaries are created", {
  data <- mi_trial_data(30, 5)
  dif <- fit_process_dif(data, "response", "dwell_ms", "group", "item_id")
  expect_s3_class(dif, "eye_process_dif")
  expect_equal(nrow(dif$summary), 5)
  drift <- monitor_dif_drift(data, "time", "group", c("dwell_ms", "pupil"), "item_id")
  expect_s3_class(drift, "eye_dif_drift")
  expect_true(all(c("slope", "n_time_points") %in% names(drift$slopes)))
  expect_true(all(is.na(drift$slopes$slope) | is.finite(drift$slopes$slope)))
  decomposition <- decompose_dif_evidence(dif)
  expect_true("evidence_pattern" %in% names(decomposition$table))
  transport <- audit_fairness_transportability(transform(dif$summary, device = rep(c("A", "B"), length.out = nrow(dif$summary))))
  expect_s3_class(transport, "eye_fairness_transportability")
  expect_plot_silent(plot_process_dif_forest(dif))
})
