#!/usr/bin/env Rscript
args <- commandArgs(trailingOnly = TRUE)
if (!length(args)) stop("Usage: aggregate-validation-program.R <manifest-dir> [report.md]")
library(eyeprocess)
path <- normalizePath(args[1L], winslash = "/", mustWork = TRUE)
report <- if (length(args) >= 2L) args[2L] else file.path(path, "validation-release-report.md")
plan <- read_validation_job_manifest(path)
collection <- collect_validation_jobs(path, plan, strict = FALSE)
audit <- audit_validation_completion(collection)
write_validation_release_report(collection, report)
write.csv(audit$gates, file.path(path, "completion-gates.csv"), row.names = FALSE)
saveRDS(audit, file.path(path, "completion-audit.rds"), version = 3)
print(audit)
if (!identical(audit$status, "complete")) quit(status = 2L)
